### ISSUE TITLE
supported/inputs/v2.0.2/VMware/inputs_vsphere_gilan_v2.0.2.yaml missing ntp_server and timezone

### ISSUE THREAD

**Issue by MicSkr** [F5Networks/f5-nfv-solutions#41]
**Describe the bug**
Missing ntp_server and timezone in yaml

https://github.com/F5Networks/f5-nfv-solutions/blob/master/supported/inputs/v2.0.2/VMware/inputs_vsphere_gilan_v2.0.2.yaml

Provide the following:
- VNFM version used: 2.0.2
- Hypervisor type and version used: vmware

**To Reproduce**
1. Compare gilan with gilan_cgnat
2. encounter differences

**Expected behavior**
I believe I was expecting ntp_server and timezone

**Comment by gabetellier** [comment]
This is being tracked internally with ESEVNFMNGR-2679.

**Comment by gabetellier** [comment]
**WORKAROUND**
If the ntp_server and timezone inputs are NOT set, then the values are automatically set to the default values:
timezone = UTC
ntp_server = NTP on your VNFM

**Comment by gabetellier** [comment]
4 files fixed by adding the following missing 3 inputs:

- datacenter
- timezone
- ntp_server
