### ISSUE TITLE
vmware gilan v3.0.0 blueprint zip missing

### ISSUE THREAD

**Issue by MicSkr** [F5Networks/f5-nfv-solutions#43]
**Describe the bug**
Is there a zip associated with this blueprint release?

Provide the following:
- Blueprint zip
- Changes

**To Reproduce**
1. Go to 'https://github.com/F5Networks/f5-nfv-solutions/tree/master/supported/blueprints/vmware/gilan/v3.0.0'

**Expected behavior**
Blueprint zip for download

**Comment by MicSkr** [comment]
This appears to be missing on the whole VMware stack. Now unsure this was an intentional release.

https://github.com/F5Networks/f5-nfv-solutions/tree/master/supported/blueprints/vmware/base/v3.0.0
https://github.com/F5Networks/f5-nfv-solutions/tree/master/supported/blueprints/vmware/big-iq/v3.0.0
https://github.com/F5Networks/f5-nfv-solutions/tree/master/supported/blueprints/vmware/cgnat/v3.0.0
https://github.com/F5Networks/f5-nfv-solutions/tree/master/supported/blueprints/vmware/dns-sec/v3.0.0
https://github.com/F5Networks/f5-nfv-solutions/tree/master/supported/blueprints/vmware/dns/v3.0.0
https://github.com/F5Networks/f5-nfv-solutions/tree/master/supported/blueprints/vmware/firewall/v3.0.0
https://github.com/F5Networks/f5-nfv-solutions/tree/master/supported/blueprints/vmware/gilan/v3.0.0


By the way, I like f5-nfv-solutions! Reach out if you would like detailed feedback on usage.

**Comment by gabetellier** [comment]
Removed 3.0 release directories. Merged by accident.
